#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(curl -fsSL https://github.com/mxcl/homebrew/blob/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo "
export CLICOLOR=1" >> ~/.profile

echo "
export LSCOLORS=GxFxCxDxBxegedabagaced" >> ~/.profile

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.profile
  source ~/.profile

echo "Installing Postgres, a good open source relational database ..."
  brew install postgres --no-python

echo "Installing Redis, a good key-value database ..."
  brew install redis

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing tmux, a good way to save project state and switch between projects ..."
  brew install tmux

echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  brew install qt

echo "Installing RVM (Ruby Version Manager) ..."
  bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.profile
  source ~/.profile

echo "Installing Ruby 1.9.3 stable and making it the default Ruby ..."
  rvm install 1.9.3
  type rvm | head -1
  sleep 5
  rvm use ruby-1.9.3
  ruby -v
  rvm --default 1.9.3

echo "Installing Rails to write and run web applications ..."
  gem install rails

echo "Installing the Heroku gem to interact with the http://heroku.com API ..."
  gem install heroku

echo "Installing the Taps gem to push and pull SQL databases between development, staging, and production environments ..."
  gem install taps

echo "Installing the pg gem to talk to Postgres databases ..."
  env ARCHFLAGS="-arch x86_64" gem install pg

echo "Installing the git_remote_branch gem for fast feature branch creating and deleting ..."
  gem install git_remote_branch

echo "Installing the foreman gem for serving your Rails apps in development mode ..."
  gem install foreman

echo "Sourcing .profile"
source ~/.profile

echo "psql should show /usr/local/bin/psql"
which psql

echo "Check Ruby Version"
ruby -v